/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Badges: typeof import('./components/Badges.vue')['default']
    Icon: typeof import('./components/Icon.vue')['default']
    Image: typeof import('./components/Image.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Swiper: typeof import('./components/Swiper.vue')['default']
    Video: typeof import('./components/Video.vue')['default']
  }
}
